@Library('juju-pipeline@master') _

def juju_model = String.format("%s-%s", params.model, uuid())
def mnist_image = String.format("mnist-test-%s", uuid())

pipeline {
    agent {
        label 'runner-amd64'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Deploy: K8s') {
            options {
                timeout(time: 2, unit: 'HOURS')
            }
            steps {
                sh "juju add-cloud --client scapestack /var/lib/jenkins/.scapestack/scapestack-cloud || true"
                sh "juju add-credential --client scapestack -f /var/lib/jenkins/.scapestack/scapestack-creds || true"
                sh "juju bootstrap scapestack ${params.controller}"
                sh "juju model-defaults -c ${params.controller} ${params.cloud} juju-http-proxy=http://squid.internal:3128"
                sh "juju model-defaults -c ${params.controller} ${params.cloud} juju-https-proxy=http://squid.internal:3128"
                sh "juju model-defaults -c ${params.controller} ${params.cloud} juju-no-proxy=127.0.0.1,localhost,::1,10.96.0.0/17"

                deployCDK(controller: params.controller,
                          cloud: params.cloud,
                          model: juju_model,
                          bundle: "${params.bundle}",
                          version_overlay: params.overlay,
                          bundle_channel: params.bundle_channel)
            }
        }

        stage('Validate') {
            options {
                timeout(time: 1, unit: 'HOURS')
            }

            steps {
                dir('jobs') {
                    sh "CONTROLLER=${params.controller} MODEL=${juju_model} TEST_IPS='${params.test_ips}' ${utils.pytest} --junit-xml=validate.xml integration/test_hacluster.py"
                }
            }
        }
    }
    post {
        cleanup {
            tearDown(params.controller)
            sh "juju remove-cloud scapestack"
        }
    }
}
