def juju_model = String.format("%s-%s", params.model, UUID.randomUUID().toString().split('-').first())
def mnist_image = String.format("mnist-test-%s", UUID.randomUUID().toString().split('-').first())

pipeline {
    agent {
        label 'amd64 && large'
    }
    options {
        disableConcurrentBuilds()
    }
    environment {
        HOME             = "/var/lib/jenkins"
        PATH             = "/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        LC_ALL           = "C.UTF-8"
        LANG             = "C.UTF-8"
        HTTP_PROXY       = "http://egress.ps7.internal:3128"
        HTTPS_PROXY      = "http://egress.ps7.internal:3128"
        http_proxy       = "http://egress.ps7.internal:3128"
        https_proxy      = "http://egress.ps7.internal:3128"
        NO_PROXY         = "localhost,127.0.0.1"
        no_proxy         = "localhost,127.0.0.1"
        SCAPESTACKCREDS  = credentials('scapestack_creds')
        SCAPESTACKCLOUD  = credentials('scapestack_cloud')
    }
    stages {
        stage('Prepare Python') {
            steps {
                sh '''#!/bin/bash
                set -eux
                python3 -m venv venv
                venv/bin/python -m pip install tox
                venv/bin/tox --recreate -e py --notest
                '''
            }
        }
        stage('Deploy: K8s') {
            options {
                timeout(time: 2, unit: 'HOURS')
            }
            steps {
                withEnv([
                    "CONTROLLER=${params.controller}",
                    "MODEL=${juju_model}",
                    "CLOUD=${params.cloud}",
                    "BUNDLE=${params.bundle}",
                    "BUNDLE_CHANNEL=${params.bundle_channel}",
                    "OVERLAY=${params.overlay}",
                ]) {
                    sh '''#!/bin/bash
                    set -eux
                    juju add-cloud --client scapestack "$SCAPESTACKCLOUD" || true
                    juju add-credential --client scapestack -f "$SCAPESTACKCREDS" || true
                    juju bootstrap scapestack "$CONTROLLER"
                    juju model-defaults -c "$CONTROLLER" "$CLOUD" juju-http-proxy="$HTTP_PROXY"
                    juju model-defaults -c "$CONTROLLER" "$CLOUD" juju-https-proxy="$HTTPS_PROXY"
                    juju model-defaults -c "$CONTROLLER" "$CLOUD" juju-no-proxy="$NO_PROXY,::1,10.96.0.0/17"

                    bundle_channel=""
                    [[ -n "$BUNDLE_CHANNEL" ]] && bundle_channel="--channel $BUNDLE_CHANNEL"
                    version_overlay=""
                    [[ -n "$OVERLAY" ]] && version_overlay="--overlay $OVERLAY"
                    juju add-model -c "$CONTROLLER" "$MODEL" "$CLOUD"
                    charm pull "$BUNDLE" $bundle_channel ./bundle-to-test
                    juju deploy -m "$CONTROLLER:$MODEL" ./bundle-to-test/bundle.yaml $version_overlay
                    juju-wait -e "$CONTROLLER:$MODEL" -w -r3 -t14400
                    '''
                }
            }
        }
        stage('Validate') {
            options {
                timeout(time: 1, unit: 'HOURS')
            }
            steps {
                withEnv([
                    "CONTROLLER=${params.controller}",
                    "MODEL=${juju_model}",
                    "TEST_IPS=${params.test_ips}",
                ]) {
                    sh '''#!/bin/bash
                    set -eux
                    cd jobs
                    CONTROLLER="$CONTROLLER" MODEL="$MODEL" TEST_IPS="$TEST_IPS" \
                        "$WORKSPACE/.tox/py/bin/pytest" --junit-xml=validate.xml integration/test_hacluster.py
                    '''
                }
            }
        }
    }
    post {
        cleanup {
            withEnv(["CONTROLLER=${params.controller}"]) {
                sh '''#!/bin/bash
                set -eux
                juju destroy-controller --destroy-all-models --destroy-storage -y "$CONTROLLER" || true
                juju remove-cloud scapestack || true
                '''
            }
        }
    }
}
