apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
    run: load-balancer-example    
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        run: load-balancer-example
    spec:
      containers:
      - image: rocks.canonical.com/cdk/google-samples/node-hello:1.0
        name: node-hello
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-world
    run: load-balancer-example
  name: hello
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world
  type: LoadBalancer
status:
  loadBalancer: {}