apiVersion: v1
kind: Secret
metadata:
  name: keystone-auth-certs
  namespace: kube-system
type: Opaque
data:
  tls.crt: {{ keystone_auth_crt }}
  tls.key: {{ keystone_auth_key }}
{% if keystone_server_ca %}
  ca.crt: {{ keystone_server_ca }}
{% endif %}