#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function juju::bootstrap
{
    python3 $WORKSPACE/jobs/integration/tigera_aws.py cleanup

    export NUM_SUBNETS=1
    if [ "$TEST_BGP" = "1" ]; then
      export NUM_SUBNETS=2
      export JOB_NAME_CUSTOM="validate-ck-calico-bgp-router-$SERIES-$SNAP_VERSION"
    fi

    python3 $WORKSPACE/jobs/integration/tigera_aws.py bootstrap

    if [ "$TEST_BGP" = "1" ]; then
      echo "Deploying bgp router"
      python3 $WORKSPACE/jobs/integration/tigera_aws.py deploy-bgp-router
    fi
}

function juju::deploy::after
{
    python3 $WORKSPACE/jobs/integration/tigera_aws.py disable-source-dest-check

    if [ "$TEST_BGP" = "1" ]; then
      python3 $WORKSPACE/jobs/integration/tigera_aws.py configure-bgp
    fi
}

function ci::cleanup::before
{
    python3 $WORKSPACE/jobs/integration/tigera_aws.py cleanup
}

###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${1:-1.19/edge}
SERIES=${2:-bionic}
JUJU_DEPLOY_BUNDLE=cs:~containers/charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=aws/us-east-2
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-calico
ARCH=${4:-amd64}
TEST_BGP=${5:0}
JOB_NAME_CUSTOM="validate-ck-calico-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)
TMP_DIR=$(mktemp -d -t ci-XXXXXXXXXX)


###############################################################################
# START
###############################################################################
ci::run
