#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

# Init
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"


function test::execute
{
    declare -n is_pass=$1
    timeout 2h pytest \
                --html="$TMPDIR/report.html" \
                jobs/integration/test_ceph.py::test_ceph \
                --cloud "$JUJU_CLOUD" \
                --model "$JUJU_MODEL" \
                --controller "$JUJU_CONTROLLER"
    ret=$?
    is_pass="True"
    if (( $ret > 0 )); then
        is_pass="False"
    fi
}


# Setup Environment
SNAP_VERSION=${1:-1.19/edge}
SERIES=${2:-bionic}
JUJU_DEPLOY_BUNDLE=cs:~containers/charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=aws/us-east-2
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-ceph
ARCH=${4:-amd64}
JOB_NAME_CUSTOM="validate-ck-ceph-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

ci::run
