#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function juju::deploy::overlay
{
    local constraints
    constraints="arch=$ARCH cores=2 mem=8G root-disk=16G"

    tee overlay.yaml <<EOF > /dev/null
series: null
default-base: $(juju::base::from_series $SERIES)
applications:
  kubernetes-control-plane:
    constraints: $constraints
    channel: $JUJU_DEPLOY_CHANNEL
    options:
      channel: $SNAP_VERSION
      allow-privileged: "true"
      sysctl: $SYSCTL
  kubernetes-worker:
    constraints: $constraints
    channel: $JUJU_DEPLOY_CHANNEL
    options:
      channel: $SNAP_VERSION
      sysctl: $SYSCTL
  calico: null
  containerd:
    options:
      no_proxy: "localhost,127.0.0.1,::1,10.246.154.0/24,10.152.183.0/24,192.168.0.0/16"
  cilium:
    charm: cilium
    channel: $JUJU_DEPLOY_CHANNEL
relations:
  - [cilium:cni, kubernetes-control-plane:cni]
  - [cilium:cni, kubernetes-worker:cni]
EOF
}

###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${1:-1.26/stable}
SYSCTL='"{net.ipv4.conf.all.forwarding: 1, net.ipv4.conf.all.rp_filter: 0, net.ipv4.neigh.default.gc_thresh1: 128, net.ipv4.neigh.default.gc_thresh2: 28672, net.ipv4.neigh.default.gc_thresh3: 32768, net.ipv6.neigh.default.gc_thresh1: 128, net.ipv6.neigh.default.gc_thresh2: 28672, net.ipv6.neigh.default.gc_thresh3: 32768, fs.inotify.max_user_instances: 8192, fs.inotify.max_user_watches: 1048576, kernel.panic: 10, kernel.panic_on_oops: 1, vm.overcommit_memory: 1}"'
SERIES=${2:-jammy}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=vsphere/Boston
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-cilium
ARCH=${4:-amd64}
JOB_NAME_CUSTOM="validate-ck-cilium-$SERIES-$ARCH-$SNAP_VERSION"
JOB_ID=$(identifier)

###############################################################################
# START
###############################################################################
ci::run
