#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function juju::deploy::overlay
{
    local constraints
    constraints="arch=$ARCH cores=2 mem=8G root-disk=16G"

    cat <<EOF > overlay.yaml
series: $SERIES
applications:
  kubernetes-control-plane:
    constraints: $constraints
    options:
      channel: $SNAP_VERSION
      allow-privileged: 'true'
  kubernetes-worker:
    constraints: $constraints
    options:
      channel: $SNAP_VERSION
EOF

    if [ "$JUJU_CLOUD" = "vsphere/Boston" ]; then
      # Deploy vsphere-integrator
      cat <<EOF >> overlay.yaml
  vsphere-integrator:
    charm: vsphere-integrator
    channel: $JUJU_DEPLOY_CHANNEL
    options:
      datastore: vsanDatastore
      folder: k8s-crew-root
    num_units: 1
    trust: true
relations:
  - ['vsphere-integrator', 'kubernetes-control-plane:vsphere']
  - ['vsphere-integrator', 'kubernetes-worker:vsphere']
EOF
    elif [ "$JUJU_CLOUD" = "aws/us-east-1" ]; then
      # Deploy aws
      cat <<EOF >> overlay.yaml
  easyrsa:
    to: null
  aws-integrator:
    charm: aws-integrator
    channel: $JUJU_DEPLOY_CHANNEL
    num_units: 1
    trust: true
relations:
  - ['aws-integrator', 'kubernetes-control-plane:aws']
  - ['aws-integrator', 'kubernetes-worker:aws']
EOF
    elif [ "$JUJU_CLOUD" = "google/us-east1" ]; then
      # Deploy google
      cat <<EOF >> overlay.yaml
  easyrsa:
    to: null
  gcp-integrator:
    charm: gcp-integrator
    channel: $JUJU_DEPLOY_CHANNEL
    num_units: 1
    trust: true
relations:
  - ['gcp-integrator', 'kubernetes-control-plane:gcp']
  - ['gcp-integrator', 'kubernetes-worker:gcp']
EOF
    elif [ "$JUJU_CLOUD" = "azure/centralus" ]; then
      # Deploy azure
      cat <<EOF >> overlay.yaml
  calico:
    options:
      cidr: 172.22.0.0/16
  easyrsa:
    to: null
  azure-integrator:
    charm: azure-integrator
    channel: $JUJU_DEPLOY_CHANNEL
    num_units: 1
    trust: true
relations:
  - ['azure-integrator', 'kubernetes-control-plane:azure']
  - ['azure-integrator', 'kubernetes-worker:azure']
EOF
    else
      >&2 echo "Unspecified cloud"
      exit -1
    fi
}

function juju::deploy
{
    juju deploy -m "$JUJU_CONTROLLER:$JUJU_MODEL" \
         --overlay overlay.yaml \
         --force \
         --channel "$JUJU_DEPLOY_CHANNEL" "$JUJU_DEPLOY_BUNDLE" \
         --trust

    ret=$?
    if (( ret > 0 )); then
        exit "$ret"
    fi
}


function test::execute
{
    declare -n is_pass=$1
    timeout -s INT 1h pytest \
        --html="report.html" \
        --full-trace \
        jobs/integration/test_integrator_charm.py \
        --cloud "$JUJU_CLOUD" \
        --model "$JUJU_MODEL" \
        --controller "$JUJU_CONTROLLER" \
        --charm-channel="$JUJU_DEPLOY_CHANNEL"
    ret=$?
    is_pass="True"
    if (( $ret > 0 )); then
        is_pass="False"
    fi

}

###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${1:-1.26/edge}
SERIES=${2:-jammy}
JUJU_DEPLOY_BUNDLE=kubernetes-core
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=${5:-vsphere/Boston}
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-integrator
ARCH=${4:-amd64}
JOB_NAME_CUSTOM="validate-ck-integrator-$JUJU_CLOUD-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

###############################################################################
# START
###############################################################################
ci::run
