#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

# Init
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

function juju::deploy
{
    tee overlay.yaml <<EOF> /dev/null
series: $SERIES
applications:
  kubernetes-control-plane:
    constraints: cores=2 mem=8G root-disk=16G
    options:
      channel: $SNAP_VERSION
  kubernetes-worker:
    constraints: instance-type=p2.xlarge
    options:
      channel: $SNAP_VERSION
EOF

    juju deploy -m "$JUJU_CONTROLLER:$JUJU_MODEL" \
         --overlay overlay.yaml \
         --force \
         --channel "$JUJU_DEPLOY_CHANNEL" "$JUJU_DEPLOY_BUNDLE"
}


# Setup Environment
SNAP_VERSION=${1:-1.24/edge}
SERIES=${2:-focal}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=aws/us-east-2
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-nvidia
ARCH=${4:-amd64}
JOB_NAME_CUSTOM="validate-ck-nvidia-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

ci::run
