#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function juju::deploy::overlay
{
    cat <<EOF > overlay.yaml
series: $SERIES
applications:
  kubernetes-control-plane:
    channel: $JUJU_DEPLOY_CHANNEL
    options:
      channel: $SNAP_VERSION
      allow-privileged: "true"
  kubernetes-worker:
    channel: $JUJU_DEPLOY_CHANNEL
    options:
      channel: $SNAP_VERSION
  calico: null
  kube-ovn:
    charm: kube-ovn
    channel: $JUJU_DEPLOY_CHANNEL
relations:
  - [kube-ovn:cni, kubernetes-control-plane:cni]
  - [kube-ovn:cni, kubernetes-worker:cni]
EOF
}

###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${SNAP_VERSION}
SERIES=${SERIES}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=edge
JUJU_CLOUD=vsphere/Boston
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-ovn
ARCH=amd64
JOB_NAME_CUSTOM="validate-ck-ovn-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

###############################################################################
# START
###############################################################################
ci::run
