#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function test::execute
{
    juju::pip::2.9

    declare -n is_pass=$1
    timeout -s INT 3h pytest \
                --html="report.html" \
                --json-report \
                --json-report-summary \
                --json-report-file="report.json" \
                --full-trace \
                jobs/integration/validation.py \
                --is-series-upgrade \
                --cloud "$JUJU_CLOUD" \
                --model "$JUJU_MODEL" \
                --controller "$JUJU_CONTROLLER"
    ret=$?
    is_pass="True"
    if (( ret == 124 )); then
        is_pass="Timeout"
    elif (( ret > 0 )); then
        is_pass="False"
    fi
}

###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${1:-1.25/stable}
SERIES=${2:-jammy}
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_CLOUD=vsphere/Boston
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-series-upgrade
ARCH=amd64
JOB_NAME_CUSTOM="validate-ck-series-upgrade-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

###############################################################################
# START
###############################################################################
ci::run
