#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

# Init
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

function test::execute
{
    declare -n is_pass=$1
    TOX_WORK_DIR="$WORKSPACE/.tox" timeout 2h tox -e py36 -- pytest \
                --html="$TMP_DIR/report.html" \
                jobs/integration/validation.py \
                --cloud "$JUJU_CLOUD" \
                --model "$JUJU_MODEL" \
                --controller "$JUJU_CONTROLLER" \
                --snapd-upgrade \
                --snapd-channel "$TEST_UPGRADE_SNAPD_CHANNEL"

    ret=$?
    is_pass="True"
    if (( $ret > 0 )); then
        is_pass="False"
    fi
}

# Setup Environment
SNAP_VERSION=${1:-1.19/edge}
SERIES=${2:-bionic}
JUJU_DEPLOY_BUNDLE=cs:~containers/charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=aws/us-east-2
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-ck-upgrade
TEST_UPGRADE_SNAPD_CHANNEL=beta
ARCH=${4:-amd64}
JOB_NAME_CUSTOM="validate-ck-snapd-upgrade-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)
TMP_DIR=$(mktemp -d -t ci-XXXXXXXXXX)

ci::venv venv_p
set +u
source "$venv_p"/bin/activate
set -u

pip install tox pip-tools
pip-sync requirements.txt

compile::env
{
    build_starttime=$(timestamp)

    juju::bootstrap

    test::execute result
    deploy_endtime=$(timestamp)

    test::report "$result" "$build_starttime" "$deploy_endtime"
    test::capture

} 2>&1 | sed -u -e "s/^/[$JUJU_CONTROLLER] /" | tee "$TMP_DIR/ci.log"
