#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

###############################################################################
# FUNCTION OVERRIDES
###############################################################################

###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${1:-1.26/edge}
SERIES=${2:-jammy}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=${5:-vsphere/Boston}
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-ck
ARCH=${4:-amd64}
JUJU_VERSION=$(juju --version | cut -f-2 -d.)
CUSTOM_CLOUD=$(echo "$JUJU_CLOUD" | cut -f1 -d/)
JOB_NAME_CUSTOM="validate-ck-$CUSTOM_CLOUD-$ARCH-$SERIES-$JUJU_VERSION-$SNAP_VERSION"
JOB_ID=$(identifier)

###############################################################################
# START
###############################################################################
ci::run
