#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function juju::deploy::overlay
{
   local constraints
   constraints="arch=$ARCH instance-type=c4.xlarge root-disk=16G"

   tee overlay.yaml <<EOF > /dev/null
series: null
default-base: $(juju::base::from_series $SERIES)
applications:
  kubernetes-control-plane:
    constraints: $constraints
    options:
      channel: $SNAP_VERSION
      allow-privileged: "true"
  kubernetes-worker:
    constraints: $constraints
    options:
      channel: $SNAP_VERSION
  ceph-mon:
    charm: ceph-mon
    channel: $CEPH_CHANNEL
    num_units: 3
  ceph-osd:
    charm: ceph-osd
    channel: $CEPH_CHANNEL
    constraints: "root-disk=32G"
    num_units: 3
    storage:
      osd-devices: 8G,1
      osd-journals: 8G,1
relations:
  - [ceph-osd:mon, ceph-mon:osd]
  - [ceph-mon:client, kubernetes-control-plane:ceph-client]
EOF
}

function juju::deploy::after
{
    python $WORKSPACE/jobs/integration/sriov_aws.py

    juju scp -m "$JUJU_CONTROLLER:$JUJU_MODEL" \
          kubernetes-control-plane/0:config "kubeconfig"
    export KUBECONFIG="kubeconfig"
    juju add-k8s k8s --controller "$JUJU_CONTROLLER"
    juju add-model -c "$JUJU_CONTROLLER" addons k8s --config test-mode=true

    tee k8s-bundle.yaml <<EOF > /dev/null
bundle: kubernetes
series: null
default-base: $(juju::base::from_series $SERIES)
applications:
  sriov-cni:
    charm: sriov-cni
    channel: $JUJU_DEPLOY_CHANNEL
    scale: 1
    trust: true
  sriov-network-device-plugin:
    charm: sriov-network-device-plugin
    channel: $JUJU_DEPLOY_CHANNEL
    scale: 1
    trust: true
    options:
      resource-list: |-
        - resourceName: sriov
          selectors:
            drivers:
            - ixgbevf
EOF

    juju deploy -m "${JUJU_CONTROLLER}:addons" ./k8s-bundle.yaml --trust
    timeout 45m juju-wait -e "${JUJU_CONTROLLER}:addons" -w
}

function test::execute
{
    juju::pip::2.9

    declare -n is_pass=$1
    timeout -s INT 2h pytest \
                --html="report.html" \
                --json-report \
                --json-report-summary \
                --json-report-file="report.json" \
                --full-trace \
                jobs/integration/validation.py \
                --cloud "$JUJU_CLOUD" \
                --model "$JUJU_MODEL" \
                --controller "$JUJU_CONTROLLER" \
                --addons-model addons
    ret=$?
    is_pass="True"
    if (( ret == 124 )); then
        is_pass="Timeout"
    elif (( ret > 0 )); then
        is_pass="False"
    fi
}

function ci::cleanup::before
{
    ci::cleanup::model::addons
}

###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${1:-1.26/edge}
SERIES=${2:-jammy}
CEPH_CHANNEL=${5:-quincy/stable}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=aws/us-east-1
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-sriov
ARCH=${4:-amd64}
JOB_NAME_CUSTOM="validate-ck-sriov-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

###############################################################################
# START
###############################################################################
ci::run
