#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function juju::bootstrap
{
    python3 $WORKSPACE/jobs/integration/tigera_aws.py cleanup
    python3 $WORKSPACE/jobs/integration/tigera_aws.py bootstrap
}

function juju::deploy::overlay
{
    cat <<EOF > overlay.yaml
series: $SERIES
applications:
  kubernetes-master:
    options:
      channel: $SNAP_VERSION
      service-cidr: "10.152.183.0/24,fd00:c00b:2::/112"
  kubernetes-worker:
    options:
      channel: $SNAP_VERSION
  flannel:
  tigera-secure-ee:
    charm: cs:~containers/tigera-secure-ee
relations:
- [tigera-secure-ee:etcd, etcd:db]
- [tigera-secure-ee:cni, kubernetes-master:cni]
- [tigera-secure-ee:cni, kubernetes-worker:cni]
- [tigera-secure-ee:kube-api-endpoint, kubernetes-master:kube-api-endpoint]
EOF
}

function juju::deploy::after
{
    juju config -m $JUJU_CONTROLLER:$JUJU_MODEL tigera-secure-ee \
        license-key=$(base64 -w0 $TIGERA_SECURE_EE_LICENSE_KEY_FILE) \
        registry-credentials=$(base64 -w0 $TIGERA_PRIVATE_REGISTRY_CREDENTIALS_FILE)

    python3 $WORKSPACE/jobs/integration/tigera_aws.py disable-source-dest-check
}

function ci::cleanup::before
{
    python3 $WORKSPACE/jobs/integration/tigera_aws.py cleanup
}

###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${1:-1.19/edge}
SERIES=${2:-bionic}
JUJU_DEPLOY_BUNDLE=cs:~containers/charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=aws/us-east-2
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-tigera-ee
ARCH=${4:-amd64}
TEST_BGP=${5:0}
JOB_NAME_CUSTOM="validate-ck-tigera-ee-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

###############################################################################
# START
###############################################################################
ci::run
