#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function juju::bootstrap
{
    # VPC with a single subnet and IPv6, created with:
    # NUM_SUBNETS=1 jobs/integration/tigera_aws.py create-vpc
    vpc_id=vpc-03f2c7351e64c6e0f

    juju bootstrap "$JUJU_CLOUD" "$JUJU_CONTROLLER" \
      -d "$JUJU_MODEL" \
      --bootstrap-series "$SERIES" \
      --force \
      --bootstrap-constraints arch="$ARCH" \
      --model-default test-mode=true \
      --model-default resource-tags=owner=k8sci \
      --model-default image-stream=daily \
      --model-default automatically-retry-hooks=true \
      --model-default logging-config="<root>=DEBUG" \
      --model-default vpc-id=$vpc_id
}

function juju::deploy
{
    juju deploy -m "$JUJU_CONTROLLER:$JUJU_MODEL" \
         --overlay overlay.yaml \
         --force \
         --channel "$JUJU_DEPLOY_CHANNEL" "$JUJU_DEPLOY_BUNDLE"

    juju config -m $JUJU_CONTROLLER:$JUJU_MODEL tigera-secure-ee \
        license-key=$(base64 -w0 $TIGERA_SECURE_EE_LICENSE_KEY_FILE) \
        registry-credentials=$(base64 -w0 $TIGERA_PRIVATE_REGISTRY_CREDENTIALS_FILE)

    python3 $WORKSPACE/jobs/integration/tigera_aws.py disable-source-dest-check
}

###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${1:-1.24/edge}
SERIES=${2:-focal}
JUJU_DEPLOY_BUNDLE=kubernetes-tigera-secure-ee
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=aws/us-east-2
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-tigera-ee
ARCH=${4:-amd64}
TEST_BGP=${5:0}
JOB_NAME_CUSTOM="validate-ck-tigera-ee-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

###############################################################################
# START
###############################################################################
ci::run
