#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function juju::bootstrap
{
    # VPC with a single subnet and IPv6, created with:
    # NUM_SUBNETS=1 jobs/integration/tigera_aws.py create-vpc
    vpc_id=vpc-03f2c7351e64c6e0f

    juju bootstrap "$JUJU_CLOUD" "$JUJU_CONTROLLER" \
      --add-model "$JUJU_MODEL" \
      --force \
      --bootstrap-base "$(juju::base::from_series $SERIES)" \
      --bootstrap-constraints arch="amd64" \
      --model-default test-mode=true \
      --model-default resource-tags=owner=$JUJU_OWNER \
      --model-default image-stream=daily \
      --model-default automatically-retry-hooks=true \
      --model-default logging-config="<root>=DEBUG" \
      --model-default vpc-id=$vpc_id
}

function juju::deploy::overlay
{
    cat <<EOF > overlay.yaml
series: null
default-base: $(juju::base::from_series $SERIES)
applications:
  kubernetes-control-plane:
    channel: $JUJU_DEPLOY_CHANNEL
    options:
      channel: $SNAP_VERSION
  kubernetes-worker:
    channel: $JUJU_DEPLOY_CHANNEL
    options:
      channel: $SNAP_VERSION
  tigera-secure-ee:
    charm: tigera-secure-ee
  calico: null
relations:
- [tigera-secure-ee:etcd, etcd:db]
- [tigera-secure-ee:cni, kubernetes-control-plane:cni]
- [tigera-secure-ee:cni, kubernetes-worker:cni]
- [tigera-secure-ee:kube-api-endpoint, kubernetes-control-plane:kube-api-endpoint]
EOF
}

function juju::deploy
{
    juju deploy -m "$JUJU_CONTROLLER:$JUJU_MODEL" \
         --overlay overlay.yaml \
         --force \
         --channel "$JUJU_DEPLOY_CHANNEL" "$JUJU_DEPLOY_BUNDLE"

    juju config -m $JUJU_CONTROLLER:$JUJU_MODEL tigera-secure-ee \
        license-key=$(base64 -w0 $TIGERA_SECURE_EE_LICENSE_KEY_FILE) \
        registry-credentials=$(base64 -w0 $TIGERA_PRIVATE_REGISTRY_CREDENTIALS_FILE)

    python3 $WORKSPACE/jobs/integration/tigera_aws.py disable-source-dest-check
}

###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${1:-1.26/edge}
SERIES=${2:-jammy}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=aws/us-east-2
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-tigera-ee
ARCH=${4:-amd64}
TEST_BGP=${5:0}
JOB_NAME_CUSTOM="validate-ck-tigera-ee-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

###############################################################################
# START
###############################################################################
ci::run
