#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function test::execute
{
    juju::pip::2.9

    declare -n is_pass=$1
    timeout -s INT 3h pytest \
                --full-trace \
                jobs/integration/validation.py \
                --is-upgrade \
                --upgrade-snap-channel "$SNAP_CHANNEL_UPGRADE_TO" \
                --upgrade-charm-channel "$CHARM_CHANNEL_UPGRADE_TO" \
                --cloud "$JUJU_CLOUD" \
                --model "$JUJU_MODEL" \
                --controller "$JUJU_CONTROLLER"
    ret=$?
    is_pass="True"
    if (( ret == 124 )); then
        is_pass="Timeout"
    elif (( ret > 0 )); then
        is_pass="False"
    fi
}

###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${1:-1.25/stable}
SERIES=${2:-jammy}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-stable}
JUJU_CLOUD=${5:-vsphere/Boston}
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-upgrade
ARCH=${4:-amd64}
JOB_NAME_CUSTOM="validate-ck-upgrade-$ARCH-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

# this job deploys with
#   charm-channel at {K8S_STABLE_VERSION}/stable
#   snap-channel  at {K8S_STABLE_VERSION - 1}/stable or {K8S_STABLE_VERSION - 2}/stable
# then upgrades charm-channel to latest/edge
# and  upgrades snap-channel  to {K8S_STABLE_VERSION}/stable

export CHARM_CHANNEL_UPGRADE_TO=latest/edge
export SNAP_CHANNEL_UPGRADE_TO=${JUJU_DEPLOY_CHANNEL}

###############################################################################
# START
###############################################################################
ci::run
