#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"


###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function juju::bootstrap
{
    local constraints
    constraints="instance-type=a1.large arch=$ARCH"

    juju bootstrap "$JUJU_CLOUD" "$JUJU_CONTROLLER" \
         -d "$JUJU_MODEL" \
         --bootstrap-series "$SERIES" \
         --force \
         --bootstrap-constraints "$constraints" \
         --model-default test-mode=true \
         --model-default resource-tags=owner=k8sci \
         --model-default automatically-retry-hooks=true \
         --model-default image-stream=daily
}

function juju::deploy
{
    local constraints
    constraints="instance-type=a1.large arch=$ARCH"

    tee overlay.yaml <<EOF> /dev/null
series: $SERIES
applications:
  easyrsa:
    constraints: $constraints
  etcd:
    constraints: $constraints
  kubeapi-load-balancer:
    constraints: $constraints
  kubernetes-control-plane:
    constraints: $constraints
    options:
      channel: $SNAP_VERSION
      controller-manager-extra-args: 'feature-gates=RotateKubeletServerCertificate=true,LegacyServiceAccountTokenNoAutoGeneration=false'
  kubernetes-worker:
    constraints: $constraints
    options:
      channel: $SNAP_VERSION
EOF
    juju deploy -m "$JUJU_CONTROLLER:$JUJU_MODEL" \
         --overlay overlay.yaml \
         --force \
         --channel "$JUJU_DEPLOY_CHANNEL" "$JUJU_DEPLOY_BUNDLE"
}

function test::execute
{
    declare -n is_pass=$1
    timeout -s INT 3h pytest \
                --full-trace \
                jobs/integration/validation.py \
                --is-upgrade \
                --upgrade-snap-channel "$SNAP_VERSION_UPGRADE_TO" \
                --upgrade-charm-channel edge \
                --cloud "$JUJU_CLOUD" \
                --model "$JUJU_MODEL" \
                --controller "$JUJU_CONTROLLER"
    ret=$?
    is_pass="True"
    if (( $ret > 0 )); then
        is_pass="False"
    fi
}

###############################################################################
# ENV
###############################################################################
SNAP_VERSION_UPGRADE_TO=${5:-1.24/edge}
export SNAP_VERSION_UPGRADE_TO

SNAP_VERSION=${1:-1.23/stable}
SERIES=${2:-focal}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-stable}
JUJU_CLOUD=aws/us-east-1
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-upgrade
ARCH=${4:-amd64}
JOB_NAME_CUSTOM="validate-ck-upgrade-$ARCH-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

###############################################################################
# START
###############################################################################
ci::run
