#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -ex

# Init
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

# Override bootstrap to use a single subnet vpc
function juju::bootstrap
{
    juju bootstrap "$JUJU_CLOUD" "$JUJU_CONTROLLER" \
         -d "$JUJU_MODEL" \
         --bootstrap-series "$SERIES" \
         --force \
         --bootstrap-constraints arch="$ARCH" \
         --model-default test-mode=true \
         --model-default resource-tags=owner=k8sci \
         --model-default image-stream=daily \
         --model-default vpc-id=vpc-0e4f11d0d4e9ba35f \
         --config vpc-id=vpc-0e4f11d0d4e9ba35f
}


# Setup Environment
LONG_ID=$(identifier)
ID=$(echo "$LONG_ID" | cut -f1 -d-)

SNAP_VERSION=${1:-1.19/edge}
SERIES=${2:-bionic}
JUJU_DEPLOY_BUNDLE=cs:~containers/charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-edge}
JUJU_CLOUD=aws/us-east-2
JUJU_CONTROLLER=validate-$ID
JUJU_MODEL=validate-vault
ARCH=${4:-amd64}
JOB_NAME_CUSTOM="validate-ck-vault-$SERIES-$SNAP_VERSION"
TMP_DIR=$(mktemp -d -t ci-XXXXXXXXXX)

compile::env
{
    build_starttime=$(timestamp)

    juju::bootstrap
    juju::deploy
    juju::wait

    deploy_endtime=$(timestamp)

    result=$(test::execute)
    test::report "$result" "$build_starttime" "$deploy_endtime"

} 2>&1 | sed -u -e "s/^/[$JUJU_CONTROLLER] /" | tee "$TMP_DIR/ci.log"
