@Library('juju-pipeline@master') _

def juju_model = String.format("%s-%s", params.model, uuid())

pipeline {
    agent {
        label 'runner-amd64'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Validate') {
            options {
                timeout(time: 2, unit: 'HOURS')
            }
            steps {
                setStartTime()
                sh "sudo snap refresh core --${params.snap_channel} || true"
                sh "juju bootstrap ${params.cloud} ${params.controller}"
                sh "juju add-model -c ${params.controller} ${juju_model} ${params.cloud}"
                dir('jobs') {
                    sh "SNAPD_CHANNEL=${params.snap_channel} CONTROLLER=${params.controller} MODEL=${juju_model} CLOUD=${params.cloud} SERIES=${params.series} SNAP_CHANNEL=${params.snap_channel} ${utils.pytest} integration/validation.py --snapd-upgrade -m 'not slow'"
                }
            }
        }
    }
    post {
        success {
            setPass()
        }

        failure {
            setFail()
        }

        always {
            setEndTime()
            collectDebug(params.controller,
                         juju_model)
        }

        cleanup {
            saveMeta()
            tearDown(params.controller)
            sh "sudo snap refresh core --candidate || true"
        }
    }
}
