@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
        CDKBOT_TOKEN = credentials('cdkbot')
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Setup') {
            steps {
                sh "snapcraft login --with ${env.CDKBOT_TOKEN}"
            }
        }
        stage('Generate Snap Report'){
            steps {
                script {
                    currentBuild.description = sh script:"bash jobs/snap-info/snap-info.sh", returnStdout: true
                }
            }
        }
    }
    post {
        always {
            sh "snapcraft logout"
        }
    }
}
