version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "requirements.txt"
    ignore:
      - dependency-name: "requirements-2.9.txt"
