EASYRSA_VERSION=${EASYRSA_VERSION:-"3.0.1"}
FLANNEL_VERSION=${FLANNEL_VERSION:-"v0.7.0"}
CNI_VERSION=${CNI_VERSION:-"v0.4.0"}
ETCD_VERSION=${ETCD_VERSION:-"v2.3.7"}
KUBE_VERSION=${KUBE_VERSION:-"v1.5.2"}
