@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = '/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin'
        CDKBOT_GH = credentials('cdkbot_github')
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Sync Upstream K8s'){
            steps {
                dir('kubernetes') {
                    git poll: true, url: 'https://github.com/juju-solutions/kubernetes'
                    sh "git config user.email 'cdkbot@juju.solutions'"
                    sh "git config user.name 'cdkbot'"
                    sh "git remote add upstream https://github.com/kubernetes/kubernetes.git"
                    sh "git fetch upstream"
                    sh "git merge upstream/master"
                    sh "git pull --tags upstream master"
                    sh "git push --tags https://${CDKBOT_GH}@github.com/juju-solutions/kubernetes master"
                }
            }
        }
    }
}
