apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  generateName: "mnist-test-"
spec:
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: "tensorflow/tensorflow:1.5.0"
              command:
                - bash
                - -c
                - curl -v https://raw.githubusercontent.com/juju-solutions/charm-kubeflow-tf-job-operator/master/files/mnist.py | python /dev/stdin --train_steps 10
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: "tensorflow/tensorflow:1.5.0"
              command:
                - bash
                - -c
                - curl -v https://raw.githubusercontent.com/juju-solutions/charm-kubeflow-tf-job-operator/master/files/mnist.py | python /dev/stdin --train_steps 10

