EASYRSA_VERSION=${EASYRSA_VERSION:-"3.0.1"}
FLANNEL_VERSION=${FLANNEL_VERSION:-"v0.9.1"}
CNI_VERSION=${CNI_VERSION:-"v0.6.0"}
ETCD_VERSION=${ETCD_VERSION:-"v2.3.8"}
KUBE_VERSION=${KUBE_VERSION:-"v1.5.5"}
