@Library('juju-pipeline@master') _

def juju_model = String.format("%s-%s", params.model, uuid())

pipeline {
    agent {
        label 'runner-amd64'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Validate') {
            options {
                timeout(time: 2, unit: 'HOURS')
            }
            steps {
                setStartTime()
                sh "juju bootstrap ${params.cloud} ${params.controller}"
                sh "juju add-model -c ${params.controller} ${juju_model} ${params.cloud}"
                dir('jobs') {
                    sh "CONTROLLER=${params.controller} MODEL=${juju_model} CLOUD=${params.cloud} SERIES=${params.series} ${utils.pytest} --junit-xml=validate.xml integration/test_docker_proposed.py::test_docker_proposed"
                }
            }
            post {
                always {
                    setEndTime()
                    collectDebug(params.controller,
                                 juju_model)
                }
            }
        }
    }
    post {
        success {
            setPass()
        }
        failure {
            setFail()
        }

        cleanup {
            saveMeta()
            tearDown(params.controller)

        }
    }
}
