@Library('juju-pipeline@master') _

def juju_model = String.format("%s-%s", params.model, uuid())

pipeline {
    agent {
        label 'runner-amd64'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Validate') {
            options {
                timeout(time: 2, unit: 'HOURS')
            }
            steps {
                sh "juju kill-controller -y ${params.controller} || true"
                sh "juju bootstrap ${params.cloud} ${params.controller} --debug"

                dir('jobs') {
                    sh "CONTROLLER=${params.controller} MODEL=${juju_model} CLOUD=${params.cloud} SERIES=${params.series} tox -e py36 -- pytest -v -s --junit-xml=validate.xml integration/test_docker_proposed.py::test_docker_proposed"
                }
            }
            post {
                always {
                    collectDebug(params.controller,
                                 juju_model)
                    dir("jobs") {
                        sh "$collect_debug_sh push results*.tar.gz"
                        sh "$collect_debug_sh push logs"
                    }

                    tearDown(params.controller,
                             juju_model)
                }
            }
        }
    }
    post {
        success {
            junit 'jobs/*.xml, jobs/logs/**/**/*.xml'
            archiveArtifacts artifacts: 'jobs/logs/*', fingerprint: true
        }
    }
}
