@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner-amd64'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
        LPCREDS = credentials('launchpad_creds')
        GITHUB_CREDS = credentials('cdkbot_github')
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Release microk8s'){
            steps {
                sh "LPCREDS=${env.LPCREDS} GH_USER='${env.GITHUB_CREDS_USR}' GH_TOKEN='${env.GITHUB_CREDS_PSW}' tox -c jobs/microk8s/tox.ini -e py36 -- python3 jobs/microk8s/update-gh-branches-and-lp-builders.py"
            }
        }
    }
}
