@Library('juju-pipeline@master') _

def exec(cmd) {
    sh "juju ssh -m ${CONTROLLER}:default ubuntu/0 -- bash -c 'cd /project && ${cmd}'"
}

pipeline {
    agent {
        label 'runner-amd64-1'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
        CONTROLLER = "validate-microk8s-${uuid()}"
    }
    options {
        ansiColor('xterm')
        timestamps()
        timeout(time: 1, unit: 'HOURS')
    }
    stages {
        stage('Set Start Time') {
            steps {
                setStartTime()
            }
        }
        stage('Setup') {
            steps {
                sh "juju bootstrap aws ${CONTROLLER}"
                sh "juju deploy -m ${CONTROLLER}:default ubuntu --constraints 'cores=4 mem=16G root-disk=40G'"
                sh "juju wait -vw -m ${CONTROLLER}:default"
                sh "juju status -m ${CONTROLLER}:default"
                sh "juju status -m ${CONTROLLER}:default --format yaml"
            }
        }
        stage('Wait for snap') {
            options {
                retry(20)
            }
            steps {
                exec "sudo snap install core"
            }
        }
        stage('Install dependencies') {
            steps {
                exec "sudo snap install charm --classic"
                exec "sudo snap install jq"
                exec "sudo snap install juju --classic --channel ${params.juju_channel}"
                exec "sudo snap install juju-helpers --classic --edge"
                exec "sudo snap alias juju-helpers.juju-bundle juju-bundle"
                exec "sudo snap install juju-wait --classic"
                exec "sudo snap install kubectl --classic"
                exec "sudo snap install microk8s --classic --channel ${params.microk8s_channel}"
                exec "sudo snap install yq"
                exec "sudo apt update && sudo apt install -y python-tox docker.io"
            }
        }
        stage('Deploy kubeflow') {
            steps {
                exec "git clone https://github.com/juju-solutions/bundle-kubeflow.git"
                exec 'echo \'PATH=$PATH:/snap/bin\' > ~/.bashrc'
                exec 'microk8s.status'
                exec 'sudo snap logs -n=100 microk8s'
                exec "cd bundle-kubeflow && CI=true BUILD=true CHANNEL=${params.channel} CHARM_BUILD_DIR=/tmp/charm-builds ./scripts/deploy-microk8s.sh"
            }
        }
        stage('Validate') {
            steps {
                exec '''
                    cd jobs/ && \
                    PY_IGNORE_IMPORTMISMATCH=1
                    CONTROLLER=uk8s
                    MODEL=kubeflow
                    tox
                        -e py36
                        --
                        pytest
                            -v
                            -s
                            --junit-xml=validate.xml
                            integration/test_kubeflow.py::test_validate
                '''.replaceAll('\\s+', ' ')
            }
        }
    }
    post {
        success {
            setPass()
        }
        failure {
            setFail()
        }
        always {
            setEndTime()
//            collectDebug(params.controller, juju_model)
        }
        cleanup {
            saveMeta()
            sh "juju destroy-controller --destroy-all-models --destroy-storage ${CONTROLLER} -yt0"
        }
    }
}
