@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin"
        JUJU_MODEL = "${params.model}-${env.BUILD_NUMBER}"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Install tools') {
            steps {
                installTools()
            }
        }
        stage('Deploy: K8s') {
            options {
                timeout(time: 1, unit: 'HOURS')
            }
            steps {
                dir('jobs') {
                script {
                        sh "CONTROLLER=${params.controller} MODEL=${env.JUJU_MODEL} tox -e py3 -- bash integration/calico/create-subnet-aws.sh"
                    }
                }
                deployCDK(params.controller,
                          env.JUJU_MODEL,
                          "cs:~containers/${params.bundle}",
                          params.overlay,
                          params.bundle_channel)
            }
        }

        stage('Validate') {
            options {
                timeout(time: 2, unit: 'HOURS')
            }

            steps {
                dir('jobs') {
                    sh "CONTROLLER=${params.controller} MODEL=${env.JUJU_MODEL} tox -e py3 -- bash integration/calico/disable_source_dest_check.sh"
                    sh "CONTROLLER=${params.controller} MODEL=${env.JUJU_MODEL} tox -e py3 -- pytest -v -s --junit-xml=validate.xml integration/test_cdk.py::test_validate"
                }
            }
        }
    }
    post {
        success {
            junit 'jobs/*.xml, jobs/logs/**/**/*.xml'
            archiveArtifacts artifacts: 'jobs/logs/*', fingerprint: true
        }
        always {
            dir('jobs') {
                script {
                    sh "tox -e py3 -- bash integration/calico/cleanup-vpc.sh"
                }
            }

            collectDebug(params.controller,
                         env.JUJU_MODEL)
            sh "juju kill-controller -y ${params.controller}"
        }
    }
}
