@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = '/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin'
        LPCREDS = credentials('LAUNCHPAD_CREDS')
        GITHUB_CREDS = credentials('cdkbot_github')
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Setup') {
            steps {
                installTools()
            }
        }
        stage('Release microk8s'){
            steps {
                dir('jobs') {
                    sh "LPCREDS=${env.LPCREDS} GH_USER='${env.GITHUB_CREDS_USR}' GH_TOKEN='${env.GITHUB_CREDS_PSW}' pipenv run microk8s/update-gh-branches-and-lp-builders.py"
                }
            }
        }
    }
}
