@Library('juju-pipeline@master') _

def exec(cmd) {
    sh "sudo lxc exec ${CONTAINER} -- bash -c 'cd . && ${cmd}'"
}

pipeline {
    agent {
        label 'runner-amd64'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
        CONTAINER = "validate-aws-${uuid()}"
        STORAGE = "validate-aws-${uuid()}"
    }
    options {
        ansiColor('xterm')
        timestamps()
        timeout(time: 1, unit: 'HOURS')
    }
    stages {
//        stage('Set Start Time') {
//            steps {
//                setStartTime()
//            }
//        }
        stage('Setup LXC') {
            steps {
                sh "sudo lxc profile show aws || sudo lxc profile copy default aws"
                sh "sudo lxc profile edit aws < jobs/validate-kubeflow-aws/lxc.profile"
                sh "sudo lxc launch -p default -p aws ubuntu:18.04 ${CONTAINER}"
                sh "sudo lxc file push -p ~/.local/share/juju/credentials.yaml ${CONTAINER}/root/.local/share/juju/credentials.yaml"
            }
        }
        stage('Wait for snap') {
            options {
                retry(10)
            }
            steps {
                exec "sudo snap install core"
            }
        }
        stage('Install dependencies') {
            steps {
                exec "sudo snap install charm --classic"
                exec "sudo snap install jq"
                exec "sudo snap install juju --classic --channel ${params.juju_channel}"
                exec "sudo snap install juju-helpers --classic --edge"
                exec "sudo snap install juju-wait --classic"
                exec "sudo snap install kubectl --classic"
                exec "sudo snap install yq"
                exec "sudo apt update && sudo apt install -y libssl-dev python3-pip"
                exec "sudo pip3 install pytest sh kfp requests pyyaml"
            }
        }
        stage('Deploy Kubeflow') {
            steps {
                exec "git clone https://github.com/juju-solutions/bundle-kubeflow.git"
                exec """
                    cd bundle-kubeflow &&
                    git checkout ${params.bundle_revision} &&
                    ./scripts/manage-cdk create --region ${params.region} &&
                    ./scripts/deploy-cdk create --build --ci
                """.replaceAll('\\s+', ' ')
            }
        }
        stage('Validate') {
            steps {
                exec "cd bundle-kubeflow && git checkout ${params.bundle_revision} && ./tests/run.sh"
            }
        }
    }
    post {
//        success {
//            setPass()
//        }
//        failure {
//            setFail()
//        }
//        always {
//            setEndTime()
//        }
        cleanup {
//            saveMeta()
            exec "juju status || true"
            exec "juju status --format yaml || true"
            exec "juju list-controllers || true"
            exec "juju list-models || true"
            exec "juju destroy-model cdkkf:kubeflow -y --destroy-storage --force || true"
            exec "juju destroy-controller -y --destroy-all-models --destroy-storage cdkkf || true"
            sh "sudo lxc delete --force ${CONTAINER} || true"
        }
    }
}
