@Library('juju-pipeline@master') _

def exec(cmd) {
    sh "sudo lxc exec ${CONTAINER} -- bash -c 'cd . && ${cmd}'"
}

pipeline {
    agent {
        label 'runner-amd64'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
        CONTAINER = "validate-aws-${uuid()}"
        STORAGE = "validate-aws-${uuid()}"
    }
    options {
        ansiColor('xterm')
        timestamps()
        timeout(time: 1, unit: 'HOURS')
    }
    stages {
        stage('Set Start Time') {
            steps {
                setStartTime()
            }
        }
        stage('Setup LXC') {
            steps {
                sh "sudo lxc profile show aws || sudo lxc profile copy default aws"
                sh "sudo lxc profile edit aws < jobs/validate-kubeflow-aws/lxc.profile"
                sh "sudo lxc launch -p default -p aws ubuntu:18.04 ${CONTAINER}"
                sh "sudo lxc file push -p ~/.local/share/juju/credentials.yaml ${CONTAINER}/root/.local/share/juju/credentials.yaml"
            }
        }
        stage('Wait for snap') {
            options {
                retry(10)
            }
            steps {
                exec "sudo snap install core"
            }
        }
        stage('Install dependencies') {
            steps {
                exec "sudo snap install charm --classic"
                exec "sudo snap install jq"
                exec "sudo snap install juju --classic --channel ${params.juju_channel}"
                exec "sudo snap install juju-helpers --classic --edge"
                exec "sudo snap install juju-wait --classic"
                exec "sudo snap install yq"
                exec "sudo snap install kubectl --classic"
                exec "sudo apt update && sudo apt install -y python-tox"
            }
        }
        stage('Deploy kubeflow') {
            steps {
                exec """
                    git clone https://github.com/juju-solutions/bundle-kubeflow.git &&
                    cd bundle-kubeflow &&
                    ./scripts/manage-cdk create --region us-east-2 &&
                    CHARM_BUILD_DIR=/tmp/charm-builds ./scripts/deploy-cdk create --build --ci --channel ${params.channel}
                """.replaceAll('\\s+', ' ')
                exec 'juju status -m default | grep "kubernetes-worker/0" | awk "{print \\$5}" > PUB_IP'
            }
        }
        stage('Validate') {
            steps {
                exec """
                    git clone https://github.com/charmed-kubernetes/jenkins.git &&
                    cd jenkins &&
                    git checkout ${env.GIT_COMMIT} &&
                    cd jobs/ &&
                    PY_IGNORE_IMPORTMISMATCH=1
                    CONTROLLER=cdkkf
                    MODEL=kubeflow
                    TOX_WORK_DIR=.tox
                    tox
                        -e py36
                        --
                        pytest
                            -v
                            -s
                            --junit-xml=validate.xml
                            integration/test_kubeflow.py::test_validate
            """.replaceAll('\\s+', ' ')
            }
        }
    }
    post {
        success {
            setPass()
        }
        failure {
            setFail()
        }
        always {
            setEndTime()
            //collectDebug(params.controller, 'default')
        }
        cleanup {
            saveMeta()
            exec "juju status || true"
            exec "juju list-controllers || true"
            exec "juju list-models || true"
            exec "juju destroy-controller -y --destroy-all-models --destroy-storage cdkkf || true"
            sh "sudo lxc delete --force ${CONTAINER} || true"
        }
    }
}
