#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"


###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function test::execute
{
    juju::pip::2.9

    declare -n is_pass=$1
    timeout -s INT 3h pytest \
                --full-trace \
                jobs/integration/validation.py \
                --is-upgrade \
                --upgrade-snap-channel "$SNAP_CHANNEL_UPGRADE_TO" \
                --upgrade-charm-channel "$CHARM_CHANNEL_UPGRADE_TO" \
                --cloud "$JUJU_CLOUD" \
                --model "$JUJU_MODEL" \
                --controller "$JUJU_CONTROLLER"
    ret=$?
    is_pass="True"
    if (( ret == 124 )); then
        is_pass="Timeout"
    elif (( ret > 0 )); then
        is_pass="False"
    fi
}

###############################################################################
# ENV
###############################################################################

SNAP_VERSION=${1}
SERIES=${2}
CANDIDATE_CHANNEL=${3}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=stable
JUJU_CLOUD=${4}
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-bugfix-upgrade
JUJU_VERSION=$(juju --version | cut -f-2 -d.)
ARCH=amd64
CUSTOM_CLOUD=$(echo "$JUJU_CLOUD" | cut -f1 -d/)
JOB_ID=$(identifier)


# this job deploys with
#   charm-channel=stable
#   snap-channel  at {K8S_STABLE_VERSION - 1}/stable or {K8S_STABLE_VERSION - 2}/stable
# then upgrades charm-channel to candidate
# and  upgrades snap-channel  to candidate
export CHARM_CHANNEL_UPGRADE_TO=${CANDIDATE_CHANNEL}
export SNAP_CHANNEL_UPGRADE_TO=${CANDIDATE_CHANNEL}

JOB_NAME_CUSTOM="validate-charm-bugfix-upgrade-$CUSTOM_CLOUD-$SERIES-$CANDIDATE_CHANNEL-$SNAP_VERSION-$JUJU_VERSION"


###############################################################################
# START
###############################################################################
ci::run
