#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"


###############################################################################
# ENV
###############################################################################
SNAP_VERSION=${1:-1.24/stable}
SERIES=${2:-focal}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=candidate
JUJU_CLOUD=aws/us-east-2
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-bugfix
ARCH=amd64
JOB_NAME_CUSTOM="validate-charm-bugfix-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)


###############################################################################
# START
###############################################################################
ci::run
