#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

# Init
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"

# Setup Environment

SNAP_VERSION=${1:-1.18/stable}
SERIES=${2:-bionic}
JUJU_DEPLOY_BUNDLE=cs:~containers/charmed-kubernetes
JUJU_DEPLOY_CHANNEL=${3:-candidate}
JUJU_CLOUD=aws/us-east-1
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-bugfix
ARCH=${4:-amd64}
JOB_NAME_CUSTOM="validate-ck-bugfix-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

ci::run
