#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"


###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function test::execute
{
    juju::pip::2.9

    declare -n is_pass=$1
    timeout -s INT 3h pytest \
                --full-trace \
                jobs/integration/validation.py \
                --is-upgrade \
                --upgrade-snap-channel "$SNAP_CHANNEL_UPGRADE_TO" \
                --upgrade-charm-channel "$CHARM_CHANNEL_UPGRADE_TO" \
                --cloud "$JUJU_CLOUD" \
                --model "$JUJU_MODEL" \
                --controller "$JUJU_CONTROLLER"
    ret=$?
    is_pass="True"
    if (( ret == 124 )); then
        is_pass="Timeout"
    elif (( ret > 0 )); then
        is_pass="False"
    fi
}

###############################################################################
# ENV
###############################################################################

SNAP_VERSION=${1:-1.27/stable}
SERIES=${2:-focal}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=stable
JUJU_CLOUD=vsphere/Boston
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-bugfix-upgrade
ARCH=amd64
JOB_NAME_CUSTOM="validate-charm-bugfix-upgrade-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

# this job deploys with
#   charm-channel at {K8S_STABLE_VERSION}/stable
#   snap-channel  at {K8S_STABLE_VERSION - 1}/stable or {K8S_STABLE_VERSION - 2}/stable
# then upgrades charm-channel to K8S_STABLE_VERSION/candidate
# and  upgrades snap-channel  to K8S_STABLE_VERSION/candidate
K8S_STABLE_VERSION=$(python -c 'from cilib.enums import K8S_STABLE_VERSION; print(K8S_STABLE_VERSION)')

export CHARM_CHANNEL_UPGRADE_TO=${K8S_STABLE_VERSION}/candidate
export SNAP_CHANNEL_UPGRADE_TO=${K8S_STABLE_VERSION}/candidate


###############################################################################
# START
###############################################################################
ci::run
