#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"


###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function test::execute
{
    juju::pip::2.9

    declare -n is_pass=$1
    timeout -s INT 3h pytest \
                --full-trace \
                jobs/integration/validation.py \
                --is-upgrade \
                --upgrade-snap-channel "$SNAP_CHANNEL_UPGRADE_TO" \
                --upgrade-charm-channel "$CHARM_CHANNEL_UPGRADE_TO" \
                --cloud "$JUJU_CLOUD" \
                --model "$JUJU_MODEL" \
                --controller "$JUJU_CONTROLLER"
    ret=$?
    is_pass="True"
    if (( ret == 124 )); then
        is_pass="Timeout"
    elif (( ret > 0 )); then
        is_pass="False"
    fi
}

###############################################################################
# ENV
###############################################################################
# This job deploys an existing stable charm and snap
# then upgrades to a candidate channel
# 
# using the candidate channel (1.xx/candidate)
#    derive the deploy charm-channel = 1.xx/stable
#    derive the deploy snap-channel = 1.(xx-N)/stable  where N=0 or 1

PRIOR_SNAP_OFFSET=${1}    # Could be 0 or 1
SERIES=${2}
CANDIDATE_CHANNEL=${3}

# replace 1.xx/(edge or candidate, or beta) with 1.xx/stable
JUJU_DEPLOY_CHANNEL=$(echo "$CANDIDATE_CHANNEL" | sed -E 's#/.*#/stable#')
PRIOR_TRACK=$(python3 $WORKSPACE/jobs/release/prior_track.py $CANDIDATE_CHANNEL $PRIOR_SNAP_OFFSET)
SNAP_VERSION="$PRIOR_TRACK/stable"

JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_CLOUD=${4}
JUJU_CONTROLLER=validate-$(identifier::short)
JUJU_MODEL=validate-bugfix-upgrade
JUJU_VERSION=$(juju --version | cut -f-2 -d.)
ARCH=amd64
CUSTOM_CLOUD=$(echo "$JUJU_CLOUD" | cut -f1 -d/)
JOB_ID=$(identifier)


# this job deploys with
#   charm-channel=1.xx/stable
#   snap-channel  at {K8S_STABLE_VERSION - 1}/stable or {K8S_STABLE_VERSION - 2}/stable
# then upgrades charm-channel to candidate
# and  upgrades snap-channel  to candidate
export CHARM_CHANNEL_UPGRADE_TO=${CANDIDATE_CHANNEL}
export SNAP_CHANNEL_UPGRADE_TO=${CANDIDATE_CHANNEL}

JOB_NAME_CUSTOM="validate-charm-bugfix-upgrade-$CUSTOM_CLOUD-$SERIES-$CANDIDATE_CHANNEL-$SNAP_VERSION-$JUJU_VERSION"


###############################################################################
# START
###############################################################################
ci::run
