@Library('juju-pipeline@master') _

def release_id = params.release_id
def tracker_sh = "cd jobs && ${utils.cipy} release/release-tracker.py --release-id ${release_id}"

pipeline {
    agent {
        label 'runner'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Promote charms to beta and candidate') {
            when {
                expression {
                    res = sh(returnStdout: true, script: "${tracker_sh} get-phase --name promote-charms").trim()
                    return res != 'pass'
                }
            }
            options {
                timeout(time: 1, unit: 'HOURS')
            }

            steps {
                build job:"promote-all-charms",
                    parameters: [string(name:'from_channel', value: params.charm_promote_from),
                                 string(name:'to_channel', value: params.charm_promote_to)]
            }
            post {
                failure {
                    sh "${tracker_sh} set-phase --name promote-charms --result fail"
                }
                success {
                    sh "${tracker_sh} set-phase --name promote-charms --result pass"
                }
            }
        }

        stage('Promote snaps to beta and candidate') {
            when {
                expression {
                    res = sh(returnStdout: true, script: "${tracker_sh} get-phase --name promote-snaps").trim()
                    return res != 'pass'
                }
            }

            options {
                timeout(time: 2, unit: 'HOURS')
            }

            steps {
                build job:"promote-all-arch-snaps",
                    parameters: [string(name:'promote_from', value: params.snaps_promote_from),
                                 string(name:'promote_to', value: params.snaps_promote_to)]
            }
            post {
                failure {
                    sh "${tracker_sh} set-phase --name promote-snaps --result fail"
                }
                success {
                    sh "${tracker_sh} set-phase --name promote-snaps --result pass"
                }
            }

        }

        stage('Validate: Conformance') {
            when {
                expression {
                    res = sh(returnStdout: true, script: "${tracker_sh} get-phase --name conformance").trim()
                    return res != 'pass'
                }
            }

            options {
                timeout(time: 4, unit: 'HOURS')
            }
            steps {
                build job:"conformance-v${k8sver}.x-canonical-kubernetes",
                    parameters: [string(name:'cloud', value: "google/us-east1"),
                                 string(name:'bundle_channel', value: 'candidate')]
            }
            post {
                failure {
                    sh "${tracker_sh} set-phase --name conformance --result fail"
                }
                success {
                    sh "${tracker_sh} set-phase --name conformance --result pass"
                }
            }
        }

        stage('Validate') {
            when {
                expression {
                    res = sh(returnStdout: true, script: "${tracker_sh} get-phase --name validate").trim()
                    return res != 'pass'
                }
            }

            options {
                timeout(time: 4, unit: 'HOURS')
            }

            steps {
                build job:"validate-v${k8sver}.x-canonical-kubernetes",
                    parameters: [string(name:'cloud', value: "aws/us-east-1"),
                                 string(name:'bundle_channel', value:'candidate'),
                                 string(name:'snap_channel', value:"${k8sver}/candidate")]
            }
            post {
                failure {
                    sh "${tracker_sh} set-phase --name validate --result fail"
                }
                success {
                    sh "${tracker_sh} set-phase --name validate --result pass"
                }
            }

        }

        stage('Validate: Localhost and Alternate Arches') {
            when {
                expression {
                    res = sh(returnStdout: true, script: "${tracker_sh} get-phase --name validate-alt").trim()
                    return res != 'pass'
                }
            }

            options {
                timeout(time: 5, unit: 'HOURS')
            }
            steps {
                script {
                    def jobs = [:]
                    def arches = ['amd64', 'arm64', 'ppc64le', 's390x']
                    arches.each { arch ->
                        jobs[arch] = {
                            stage(String.format("Validate arch: %s", arch)) {
                                build job:"validate-alt-${arch}-v${k8sver}.x-canonical-kubernetes",
                                    parameters: [string(name:'bundle_channel', value:'candidate'),
                                                 string(name:'snap_channel', value:"${k8sver}/candidate")]

                            }
                        }
                    }
                    parallel jobs
                }
            }
            post {
                failure {
                    sh "${tracker_sh} set-phase --name validate-alt --result fail"
                }
                success {
                    sh "${tracker_sh} set-phase --name validate-alt --result pass"
                }
            }

        }

        stage('Validate: Minor Upgrades') {
            when {
                expression {
                    res = sh(returnStdout: true, script: "${tracker_sh} get-phase --name validate-upgrade").trim()
                    return res != 'pass'
                }
            }

            options {
                timeout(time: 4, unit: 'HOURS')
            }
            steps {
                build job:"validate-minor-upgrade-${k8sver_range}-canonical-kubernetes",
                    parameters: [string(name:'cloud', value: "aws/us-east-1"),
                                 string(name:'upgrade_snap_channel', value:"${k8sver}/candidate")]

            }
            post {
                failure {
                    sh "${tracker_sh} set-phase --name validate-upgrade --result fail"
                }
                success {
                    sh "${tracker_sh} set-phase --name validate-upgrade --result pass"
                }
            }
        }
    }
}
