#!/bin/bash
# shellcheck disable=SC2034,SC1090

set -x

###############################################################################
# INITIALIZE
###############################################################################
: "${WORKSPACE:=$(pwd)}"

. "$WORKSPACE/ci.bash"
. "$WORKSPACE/juju.bash"


###############################################################################
# FUNCTION OVERRIDES
###############################################################################
function test::execute
{
    juju::pip::2.9

    declare -n is_pass=$1
    # 4h: the charm and snap upgrade runs before the first test (~25m)
    timeout -s INT 4h pytest \
                --full-trace \
                jobs/integration/validation.py \
                --is-upgrade \
                --upgrade-snap-channel "$SNAP_CHANNEL_UPGRADE_TO" \
                --upgrade-charm-channel "$CHARM_CHANNEL_UPGRADE_TO" \
                --cloud "$JUJU_CLOUD" \
                --model "$JUJU_MODEL" \
                --controller "$JUJU_CONTROLLER"
    ret=$?
    is_pass="True"
    if (( ret == 124 )); then
        is_pass="Timeout"
    elif (( ret > 0 )); then
        is_pass="False"
    fi
}

###############################################################################
# ENV
###############################################################################
export CHARM_CHANNEL_UPGRADE_TO=beta
export SNAP_CHANNEL_UPGRADE_TO=${1:-1.27/beta}

# 2nd argument: how many tracks before the upgrade target the deployed snap is
PRIOR_SNAP_OFFSET=${2:-1}
PRIOR_TRACK=$(python3 "$WORKSPACE/jobs/release/prior_track.py" "$SNAP_CHANNEL_UPGRADE_TO" "$PRIOR_SNAP_OFFSET")
SNAP_VERSION="$PRIOR_TRACK/stable"
SERIES=${3:-jammy}
JUJU_CLOUD=${4:-vsphere/Boston}
JUJU_DEPLOY_BUNDLE=charmed-kubernetes
JUJU_DEPLOY_CHANNEL=stable
JUJU_CONTROLLER=${JUJU_CONTROLLER:-validate-$(identifier::short)}
JUJU_MODEL=validate-release-upgrade
ARCH=amd64
JOB_NAME_CUSTOM="validate-charm-release-upgrade-$SERIES-$SNAP_VERSION"
JOB_ID=$(identifier)

###############################################################################
# START
###############################################################################
ci::run
