@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin"
        JUJU_MODEL = "${params.model}-${env.BUILD_NUMBER}"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Install tools') {
            steps {
                installTools()
            }
        }
        stage("Deploy") {
            options {
                timeout(time: 1, unit: 'HOURS')
            }
            steps {
                deployCDK(params.controller,
                          env.JUJU_MODEL,
                          params.bundle,
                          params.version_overlay,
                          params.bundle_channel)
            }
        }

        stage("Validate Minor Upgrade") {
            options {
                timeout(time: 1, unit: 'HOURS')
            }
            steps {
                dir('jobs') {
                    sh "TEST_SNAP_CHANNEL=${params.upgrade_snap_channel} CONTROLLER=${params.controller} MODEL=${env.JUJU_MODEL} tox -e py3 -- pytest -v -s --junit-xml=validate-upgrade.xml integration/test_cdk.py::test_upgrade"
                }
            }
        }
    }
    post {
        success {
            junit 'jobs/*.xml, jobs/logs/**/**/*.xml'
            archiveArtifacts artifacts: 'jobs/logs/*', fingerprint: true
        }
        always {
            collectDebug(params.controller,
                         env.JUJU_MODEL)
            tearDown(params.controller,
                     env.JUJU_MODEL)
        }
    }
}
