@Library('juju-pipeline@master') _

def juju_model = String.format("%s-%s", params.model, uuid())
def juju_controller = String.format("%s-%s", params.controller, uuid())

pipeline {
    agent {
        label 'runner-cloud'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage("Deploy") {
            options {
                timeout(time: 4, unit: 'HOURS')
            }
            steps {
                setStartTime()
                sh "juju bootstrap ${params.cloud} ${juju_controller} --bootstrap-constraints arch=amd64"
                deployCDK(controller: juju_controller,
                          model: juju_model,
                          cloud: params.cloud,
                          bundle: params.bundle)
            }
        }

        stage("Validate Minor Upgrade") {
            options {
                timeout(time: 4, unit: 'HOURS')
            }
            steps {
                dir('jobs') {
                    sh "TEST_UPGRADE=1 TEST_CHARM_CHANNEL=${params.upgrade_charm_channel} TEST_SNAP_CHANNEL=${params.upgrade_snap_channel} CONTROLLER=${juju_controller} MODEL=${juju_model} CLOUD=${params.cloud} ${utils.pytest} --junit-xml=validate-upgrade.xml integration/validation.py -m 'not slow'"
                }
            }
        }
    }
    post {
        success {
            setPass()
        }
        failure {
            setFail()
        }
        always {
            setEndTime()
            collectDebug(juju_controller,
                         juju_model)

        }
        cleanup {
            saveMeta()
            tearDown(juju_controller)
        }
    }
}
