@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin"
        JUJU_MODEL = "${params.model}-${env.BUILD_NUMBER}"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }

    stages {
        stage('Setup') {
            steps {
                installTools()
            }
        }
        stage("Deploy") {
            options {
                timeout(time: 1, unit: 'HOURS')
            }
            steps {
                deployCDK(params.controller,
                          env.JUJU_MODEL,
                          params.bundle,
                          params.version_overlay,
                          params.bundle_channel,
                          true)
            }
        }
        stage('Deploy: sonobuoy') {
            steps {
                deploySonobuoy(params.controller, env.JUJU_MODEL)
            }
        }
        stage('Test') {
            options {
                timeout(time: 2, unit: 'HOURS')
            }
            steps {
                waitUntil {
                    sh './sonobuoy status || true'
                    script {
                        def r = sh script:'./sonobuoy status|grep -q \'Sonobuoy has completed\'', returnStatus: true
                        return (r == 0);
                    }
                }
            }
        }
        stage('Archive') {
            steps {
                waitUntil {
                    script {
                        def r = sh script:'./sonobuoy retrieve results/.', returnStatus: true
                        return (r == 0);
                    }
                }
                archiveArtifacts artifacts: 'results/*.tar.gz'
            }
        }
    }
    post {
        always {
            tearDown(params.controller,
                     env.JUJU_MODEL)
        }
    }
}
