@Library('juju-pipeline@master') _

def juju_model = String.format("%s-%s", params.model, uuid())
def juju_controller = String.format("%s-%s", params.controller, uuid())

pipeline {
    agent {
        label params.build_node
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }

    stages {
        stage("Deploy") {
            options {
                timeout(time: 4, unit: 'HOURS')
            }
            steps {
                sh "juju kill-controller -y ${juju_controller} || true"
                sh "juju bootstrap ${params.cloud} ${juju_controller} --debug"
                setStartTime()
                deployCDK(controller: juju_controller,
                          model: juju_model,
                          bundle: "cs:~containers/${params.bundle}",
                          version_overlay: params.version_overlay,
                          cloud: params.cloud,
                          bundle_channel: params.bundle_channel,
                          allow_privileged: true)
            }
        }
        stage('Deploy: sonobuoy') {
            steps {
                deploySonobuoy(juju_controller, juju_model)
            }
        }
        stage('Test') {
            options {
                timeout(time: 3, unit: 'HOURS')
            }
            steps {
                waitUntil {
                    sh './sonobuoy status || true'
                    script {
                        def r = sh script:'./sonobuoy status|grep -q \'Sonobuoy has completed\'', returnStatus: true
                        return (r == 0);
                    }
                }
            }
        }
        stage('Archive') {
            steps {
                waitUntil {
                    script {
                        def r = sh script:'./sonobuoy retrieve results/.', returnStatus: true
                        return (r == 0);
                    }
                }
                archiveArtifacts artifacts: 'results/*.tar.gz'
            }
        }
    }
    post {
        success {
            setPass()
        }
        failure {
            setFail()
        }
        always {
            setEndTime()
            collectDebug(juju_controller,
                         juju_model)
        }
        cleanup {
            saveMeta()
            sh "juju kill-controller -y ${juju_controller} || true"
        }
    }
}
