# -*- mode:yaml; -*-
- calico:
    downstream: 'charmed-kubernetes/layer-calico.git'
    resource_build_sh: 'build-calico-resource.sh'
    namespace: 'containers'
    tags: ['k8s', 'calico']
- canal:
    downstream: 'charmed-kubernetes/layer-canal.git'
    resource_build_sh: 'build-canal-resources.sh'
    namespace: 'containers'
    tags: ['k8s', 'canal']
- containerd:
    downstream: 'charmed-kubernetes/charm-containerd.git'
    namespace: 'containers'
    tags: ['k8s', 'containerd']
- docker:
    downstream: 'charmed-kubernetes/charm-docker.git'
    namespace: 'containers'
    tags: ['k8s', 'docker']
- easyrsa:
    downstream: 'charmed-kubernetes/layer-easyrsa.git'
    namespace: 'containers'
    tags: ['k8s', 'easyrsa']
- etcd:
    downstream: 'charmed-kubernetes/layer-etcd.git'
    namespace: 'containers'
    tags: ['k8s', 'etcd']
- flannel:
    downstream: 'charmed-kubernetes/charm-flannel.git'
    resource_build_sh: 'build-flannel-resources.sh'
    namespace: 'containers'
    tags: ['k8s', 'flannel']
- kubeapi-load-balancer:
    downstream: 'charmed-kubernetes/charm-kubeapi-load-balancer.git'
    namespace: 'containers'
    tags: ['k8s', 'kubeapi-load-balancer']
- kubernetes-e2e:
    downstream: 'charmed-kubernetes/charm-kubernetes-e2e.git'
    namespace: 'containers'
    tags: ['k8s', 'kubernetes-e2e']
- kubernetes-master:
    downstream: 'charmed-kubernetes/charm-kubernetes-master.git'
    namespace: 'containers'
    tags: ['k8s', 'kubernetes-master']
- kubernetes-worker:
    downstream: 'charmed-kubernetes/charm-kubernetes-worker.git'
    resource_build_sh: 'build-cni-resources.sh'
    namespace: 'containers'
    tags: ['k8s', 'kubernetes-worker']
- tigera-secure-ee:
    downstream: 'charmed-kubernetes/layer-tigera-secure-ee.git'
    resource_build_sh: 'build-resources.sh'
    namespace: 'containers'
    tags: ['k8s', 'tigera-secure-ee']
- keepalived:
    downstream: 'https://github.com/juju-solutions/charm-keepalived.git'
    namespace: 'containers'
    tags: ['general', 'keepalived']
- docker-registry:
    downstream: 'https://github.com/CanonicalLtd/docker-registry-charm.git'
    namespace: 'containers'
    tags: ['general', 'docker-registry']
- kubeflow-ambassador:
    namespace: 'kubeflow-charmers'
    downstream: 'https://github.com/juju-solutions/charm-kubeflow-ambassador.git'
    tags: ['general', 'kubeflow-ambassador']
- kubeflow-jupyterhub:
    namespace: 'kubeflow-charmers'
    downstream: 'https://github.com/juju-solutions/charm-kubeflow-jupyterhub.git'
    tags: ['general', 'kubeflow-jupyterhub']
- kubeflow-pytorch-operator:
    namespace: 'kubeflow-charmers'
    downstream: 'https://github.com/juju-solutions/charm-kubeflow-pytorch-operator.git'
    tags: ['general', 'kubeflow-pytorch-operator']
- kubeflow-seldon-api-frontend:
    namespace: 'kubeflow-charmers'
    downstream: 'https://github.com/juju-solutions/charm-kubeflow-seldon-api-frontend.git'
    tags: ['general', 'kubeflow-seldon-api-frontend']
- kubeflow-seldon-cluster-manager:
    namespace: 'kubeflow-charmers'
    downstream: 'https://github.com/juju-solutions/charm-kubeflow-seldon-cluster-manager.git'
    tags: ['general', 'kubeflow-seldon-cluster-manager']
- kubeflow-tf-job-dashboard:
    namespace: 'kubeflow-charmers'
    downstream: 'https://github.com/juju-solutions/charm-kubeflow-tf-job-dashboard.git'
    tags: ['general', 'kubeflow-tf-job-dashboard']
- kubeflow-tf-job-operator:
    namespace: 'kubeflow-charmers'
    downstream: 'https://github.com/juju-solutions/charm-kubeflow-tf-job-operator.git'
    tags: ['general', 'kubeflow-tf-job-operator']
- kubeflow-tf-serving:
    namespace: 'kubeflow-charmers'
    downstream: 'https://github.com/juju-solutions/charm-kubeflow-tf-serving.git'
    tags: ['general', 'kubeflow-tf-serving']
- redis-k8s:
    namespace: 'kubeflow-charmers'
    downstream: 'https://github.com/juju-solutions/charm-redis-k8s.git'
    tags: ['general', 'redis-k8s']
