@Library('juju-pipeline@master') _

pipeline {
    agent {
        label "${params.build_node}"
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
    }
    options {
        ansiColor('xterm')
        timestamps()
        timeout(time: 4, unit: 'HOURS')
    }
    stages {
        stage('Provision VM') {
            steps {
                tearDown(params.controller)
                sh "juju bootstrap ${params.cloud} ${params.controller} -d microk8s-model --constraints arch=${params.arch}"
                sh "juju deploy -m ${params.controller}:microk8s-model ubuntu --constraints 'cores=8 mem=32G root-disk=80G'"
                /* g3s.xlarge and p2.xlarge are for gpu
                   a1.2xlarge for arm, t2.xlarge for amd64
                */
                sh "while ! juju show-status -m ${params.controller}:microk8s-model --format short ubuntu/0 | grep active ; do sleep 10 ; echo waiting... ; done"
            }
        }
        stage('Prepare VM') {
            steps {
                sh "juju run -m ${params.controller}:microk8s-model --unit ubuntu/0 'sudo snap install lxd'"
                sh "juju run -m ${params.controller}:microk8s-model --unit ubuntu/0 --timeout=60m0s 'sudo lxd.migrate -yes'"
                sh "juju run -m ${params.controller}:microk8s-model --unit ubuntu/0 --timeout=60m0s 'sudo lxd init --auto'"
                sh "juju run -m ${params.controller}:microk8s-model --unit ubuntu/0 'sudo snap install snapcraft --classic'"
            }
        }
        stage('Setup') {
            steps {
                retry(3) {
                    sh "snapcraft login --with /var/lib/jenkins/snapcraft-creds"
                }
            }
        }
        stage('Build and Release'){
            steps {
                retry(3) {
                    sh "DRY_RUN=${params.DRY_RUN} ALWAYS_RELEASE=${params.ALWAYS_RELEASE} TRACKS=${params.TRACKS} JUJU_UNIT=ubuntu/0 JUJU_CONTROLLER=${params.controller}:microk8s-model tox -c jobs/microk8s/tox.ini -e py36 -- python3 jobs/microk8s/release-pre-releases.py"
                }
            }
        }
    }

    /* We assume that there are no other lxc machines on the slave. */
    post {
        cleanup {
            tearDown(params.controller)
        }
    }
}
