@Library('juju-pipeline@master') _

def to_channels = params.to_channel.split()
def charm_sh = "${utils.cipy} build-charms/charms.py"

pipeline {
    agent {
        label 'runner'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Release Charm') {
            steps {
                dir('jobs') {
                    script {
                        to_channels.each { to_channel ->
                            sh "${charm_sh} promote --charm-entity cs:~${params.charm} --from-channel ${params.from_channel} --to-channel ${to_channel.trim()}"
                        }
                    }
                }
            }
        }
    }
}
