@Library('juju-pipeline@master') _

def to_channels = params.to_channel.split()

pipeline {
    agent {
        label 'runner'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = '/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin'
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Release Charm') {
            steps {
                script {
                    to_channels.each { to_channel ->
                        sh "CHARM='cs:~containers/${params.charm}' FROM_CHANNEL='${params.from_channel}' TO_CHANNEL='${to_channel.trim()}' jobs/build-charms/promote-charm.sh"
                    }
                }
            }
        }
    }
}
