@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = '/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin'
        // CDKBOT_TOKEN = credentials('cdkbot')
        GITHUB_CREDS = credentials('cdkbot_github')
    }
    parameters {
        booleanParam(name: 'FORCE_RELEASE', defaultValue: false, description: 'Force a snap release regardless of status')
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Setup') {
            steps {
                installTools()
                // sh "snapcraft login --with ${env.CDKBOT_TOKEN}"
            }
        }
        stage('Release Snaps'){
            steps {
                sh "FORCE_RELEASE=${params.FORCE_RELEASE} GH_USER=${env.GITHUB_CREDS_USR} GH_TOKEN=${env.GITHUB_CREDS_PSW} bash jobs/build-snaps/release.sh"
            }
        }
    }
    post {
        always {
            sh "sudo chown -R ubuntu:ubuntu release/snap || true"
            // sh "snapcraft logout"
        }
    }
}
