@Library('juju-pipeline@master') _

def juju_model = String.format("%s-%s", params.model, uuid())

pipeline {
    agent { label 'runner-amd64' }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Setup') {
            steps {
                sh "sudo snap install conjure-up --classic || true"
                sh "juju kill-controller -y ${params.controller} || true"
            }
        }
        stage('Deploy') {
            options {
                timeout(time: 2, unit: 'HOURS')
            }

            steps {
                dir("jobs") {
                    sh "conjure-up canonical-kubernetes ${params.cloud} ${params.controller} ${juju_model} --channel ${params.bundle_channel}"
                }
            }
        }

        stage('Test') {
            options {
                timeout(time: 2, unit: 'HOURS')
            }

            steps {
                dir("jobs") {
                    sh "CONTROLLER=${params.controller} MODEL=${juju_model} CLOUD=${params.cloud} tox -e py36 -- pytest -v -s --junit-xml=validate.xml integration/test_cdk.py::test_validate"
                }
            }
        }
    }
    post {
        always {
            collectDebug(params.controller,
                         juju_model)
            sh "juju kill-controller -y ${params.controller} || true"
        }
    }
}
