@Library('juju-pipeline@master') _

def juju_model = String.format("%s-%s", params.model, uuid())
def juju_controller = String.format("%s-%s", params.controller, uuid())

pipeline {
    agent { label 'runner-amd64' }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Deploy') {
            options {
                timeout(time: 4, unit: 'HOURS')
            }

            steps {
                setStartTime()
                dir("jobs") {
                    sh "conjure-up charmed-kubernetes ${params.cloud} ${juju_controller} ${juju_model} --channel ${params.bundle_channel}"
                }
            }
        }

        // stage('Test') {
        //     options {
        //         timeout(time: 2, unit: 'HOURS')
        //     }

        //     steps {
        //         dir("jobs") {
        //             sh "CONTROLLER=${juju_controller} MODEL=${juju_model} CLOUD=${params.cloud} ${utils.pytest}"
        //         }
        //     }
        // }
    }
    post {
        success {
            setPass()
        }
        failure {
            setFail()
        }
        always {
            setEndTime()
            collectDebug(juju_controller,
                         juju_model)
        }
        cleanup {
            saveMeta()
            tearDown(juju_controller)
        }
    }
}
