@Library('juju-pipeline@master') _

def juju_model = String.format("%s-%s", params.model, uuid())
def juju_controller = String.format("%s-%s", params.controller, uuid())

pipeline {
    agent {
        label 'runner-cloud'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Deploy: K8s') {
            options {
                timeout(time: 1.5, unit: 'HOURS')
            }
            steps {
                sh "juju bootstrap ${params.cloud} ${juju_controller} --debug"
                deployCDK(controller: juju_controller,
                          model: juju_model,
                          cloud: params.cloud,
                          bundle: "cs:~containers/${params.bundle}",
                          version_overlay: params.version_overlay,
                          bundle_channel: params.bundle_channel)
            }
        }

        stage('Validate') {
            options {
                timeout(time: 2, unit: 'hours')
            }

            steps {
                dir('jobs') {
                    sh "CONTROLLER=${juju_controller} MODEL=${juju_model} ${utils.pytest} CONTAINERD_RUNTIME_VERSION=${params.containerd_runtime_version} DOCKER_RUNTIME_VERSION=${params.docker_runtime_version} --junit-xml=validate.xml integration/test_juju_https_proxy.py::test_http_conf_existing_container_runtime"
                }
            }
        }
    }
    post {
        cleanup {
            tearDown(juju_controller)
        }
    }
}
