@Library('juju-pipeline@master') _

def generate_reports_sh = "${utils.cipy} reports/generate-reports.py"

pipeline {
    agent {
        label "runner"
    }
    // Add environment credentials for pyjenkins script on configuring nodes automagically
    environment {
        PATH = "${utils.cipaths}"
    }

    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Running') {
            steps {
                dir("jobs") {
                    sh "snapcraft login --with /var/lib/jenkins/snapcraft-creds"
                    sh "${generate_reports_sh} build"
                }
            }
        }
    }
}
