@Library('juju-pipeline@master') _

def generate_reports_sh = "${utils.cipy} reports/generate-reports.py"
def ogc = "${utils.cibin}/ogc"

pipeline {
    agent {
        label "runner"
    }
    // Add environment credentials for pyjenkins script on configuring nodes automagically
    environment {
        PATH = "${utils.cipaths}"
    }

    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Running') {
            steps {
                dir("jobs") {
                    sh "snapcraft login --with /var/lib/jenkins/snapcraft-creds"
                    sh "${ogc} report build-report --template-path reports/templates --out-path pages --report-plan includes/k8s-report-plan.yaml"
                }
            }
        }
    }
}
