@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner-amd64'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = '/snap/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin'
        LPCREDS = credentials('launchpad_creds')
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Release microk8s'){
            steps {
                dir('jobs') {
                    sh "LPCREDS=${env.LPCREDS} tox -e py36 -- python3 microk8s/release-to-edge-on-new-upstream-release.py"
                }
            }
        }
    }
}
