@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner-amd64'
    }
    /* XXX: Global $PATH setting doesn't translate properly in pipelines
     https://stackoverflow.com/questions/43987005/jenkins-does-not-recognize-command-sh
     */
    environment {
        PATH = "${utils.cipaths}"
        LPCREDS = credentials('launchpad_creds')
    }
    options {
        ansiColor('xterm')
        timestamps()
        timeout(time: 1, unit: 'HOURS')
    }
    stages {
       stage('Setup') {
            steps {
                sh "snapcraft login --with /var/lib/jenkins/snapcraft-creds"
            }
        }
        stage('Release microk8s'){
            steps {
                sh "LPCREDS=${env.LPCREDS} tox -c jobs/microk8s/tox.ini -e py36 -- python3 jobs/microk8s/release-to-edge-on-new-upstream-release.py"
            }
        }
    }
}
