apiVersion: v1
kind: ConfigMap
metadata:
  name: test-audit-webhook
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          return 200;
        }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: test-audit-webhook
spec:
  volumes:
  - name: nginx-config
    configMap:
      name: test-audit-webhook
  containers:
  - name: nginx
    image: rocks.canonical.com/cdk/nginx:1.18
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx
