name: Repo Status
on: [pull_request]

jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"

  build:
    name: Verify
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install deps
        run: |
          pip install tox
          python3 -m tox --recreate -e test --notest
          sudo snap install charmcraft --classic
      - name: Test
        run: |
          python3 -m tox -e test

