name: Repo Status
on: [push, pull_request]

jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical-web-and-design/Inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"

  build:
    name: Verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install deps
        run: |
          sudo snap install charmcraft --classic
          python -m pip install --upgrade pip
          pip install pip-tools -r requirements.txt
      - name: Test
        run: PYTHONPATH=$PYTHONPATH:$(pwd) invoke test
