@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner'
    }
    environment {
        PATH = "${utils.cipaths}"
        CDKBOT_GH = credentials('cdkbot_github')
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Sync Repos'){
            steps {
                dir("jobs") {
                    sh "CDKBOT_GH=${CDKBOT_GH} ${utils.cipy} sync-upstream/sync.py ${utils.debug_out}"
                }
            }
        }
    }
}
