@Library('juju-pipeline@master') _

pipeline {
    agent {
        label 'runner'
    }
    environment {
        PATH = "${utils.cipaths}"
        CDKBOT_GH = credentials('cdkbot_github')
    }
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
        stage('Sync Repos'){
            steps {
                sh "CDKBOT_GH=${CDKBOT_GH} ${utils.cipy} jobs/sync-upstream/sync.py"
            }
        }
    }
}
